language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: clbarnes
  password:
    secure: J14bbXOKcab80YHCdJRszfVQjE/Fh1LMvtbGffnalitmIXZLR7kBVjL0bgLy8fYj4zYnVBhBuyJ29TKPCtypPzpRluWgiujR5g+Gu8xOC48dMKLXnOpiWlKuKhx4fcfNQX6ngKUXMY7Mnbd2L52B8dEGCBIAXEpQgf34IRT2EThS8waX/OuTxu1AQ1OKFMUHwcL4Ue8wG6tb6uq58lfSCcuFAstsmSEhZIQzJugbQ1EuI97PsZiY4o9kx5UTvx5vCTFL2xuCHlpJc7efjhzkZY5fPv3/4Qci8xDoFkYIFwwcPiTE8fca3zodYLUykZ+plintUTZ1zl0SfJ6bpTTXHKATNXnbOAdRcO5RZRpvxzuCYA9zN9OmsnbPaC3ls+VEpbEd9ghqUlHHgvCpq3e9DQPkzPIlmWeixZJOuuOYtQNszrGWx5o5J9NRPkhfChbPkqyU0bfIKBuaiYbIg5C71GN3Fk/iY17UAhobC5AznFwwnjAPKgpcTYlcQqoPCAT/q7Wl5YWtaEp54LgkqQ5v1tcLKytiRw8YegMVElogr8nMktDsA6M2alBsmc+PZ493CGFpYB1qHgFxEkosV1qnYYqJTomFP/Hg3ZH3GDl7ac2oPPHnI+sy62uzIxT9VuDYGS/aXJp7ALzeObm1N2sqcr6MwVwc4w75iOmk3Wz/SvI=
  on:
    tags: true
    repo: clbarnes/f_it
    python: 3.7
